name: Super-Linter

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "10 6 * * *"  # Runs every day at 00:30 UTC (~6:00 AM IST)
  workflow_dispatch:

jobs:
  super-lint:
    
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: 23f3004293@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
